DROP TABLE `USER` ;
CREATE TABLE `USER` (
  `ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(32) NOT NULL,
  `PASSWORD` varchar(32) NOT NULL,
  `FIRSTNAME` varchar(32) NOT NULL,
  `LASTNAME` varchar(32) DEFAULT NULL,
  `EMAIL` varchar(512) NOT NULL,
  `MOBILE` varchar(32) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
   `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`)
);

DROP TABLE `ROLES` ;
CREATE TABLE `ROLES` (
  `ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(32) NOT NULL,
  `ROLE_DESC` varchar(32) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ROLE_NAME` (`ROLE_NAME`)
);

DROP TABLE `USER_ROLES` ;
CREATE TABLE `USER_ROLES` (
  `USER_ID` smallint(6) NOT NULL,
  `ROLE_ID` smallint(6) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE `PERMISSIONS` ;
CREATE TABLE `PERMISSIONS` (
	`ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `PERMISSION` varchar(32) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
  UNIQUE KEY `PERMISSION` (`PERMISSION`)
);

DROP TABLE `ROLES_PERMISSIONS` ;
CREATE TABLE `ROLES_PERMISSIONS` (
  `ROLE_ID` smallint(6) NOT NULL,
  `PERMISSION_ID` smallint(6) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE COURSE;
CREATE TABLE `COURSE` (
   ID bigint(20) NOT NULL AUTO_INCREMENT,
   NAME varchar(256) NOT NULL,
   DESCRIPTION text,
   CATEGORY_ID bigint(20) NOT NULL,
   ACTIVE char(1) NULL,
   KEY_WORDS varchar(256) NULL,
   CREATEDBY  bigint(20) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE `CASE`;
CREATE TABLE `CASE` (
   ID bigint(20) NOT NULL AUTO_INCREMENT,
   CASE_TYPE varchar(128) NOT NULL,
   DESCRIPTION text,
   STATUS smallint(20) NOT NULL,
   CATEGORY smallint(20) NOT NULL,
   ACTIVE char(1) NULL,
   CREATEDBY  bigint(20) NOT NULL,
   MODIFIED_BY  bigint(20) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


DROP TABLE `CASE_TRANSITION`;
CREATE TABLE `CASE_TRANSITION` (
   ID bigint(20) NOT NULL AUTO_INCREMENT,
   CASE_ID varchar(128) NOT NULL,
   FSTATE smallint(20) NOT NULL,
   TSTATE smallint(20) NOT NULL,
   REMARKS varchar(256) NOT NULL,
   CREATEDBY  bigint(20) NOT NULL,
   MODIFIED_BY  bigint(20) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


