DROP TABLE `USER` ;
CREATE TABLE `USER` (
  `ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(32) NOT NULL,
  `PASSWORD` varchar(32) NOT NULL,
  `FIRSTNAME` varchar(32) NOT NULL,
  `LASTNAME` varchar(32) DEFAULT NULL,
  `EMAIL` varchar(512) NOT NULL,
  `MOBILE` varchar(32) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
   `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`)
);

DROP TABLE `ROLES` ;
CREATE TABLE `ROLES` (
  `ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(32) NOT NULL,
  `ROLE_DESC` varchar(32) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ROLE_NAME` (`ROLE_NAME`)
);

DROP TABLE `USER_ROLES` ;
CREATE TABLE `USER_ROLES` (
  `USER_ID` smallint(6) NOT NULL,
  `ROLE_ID` smallint(6) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL,
);

DROP TABLE `PERMISSIONS` ;
CREATE TABLE `PERMISSIONS` (
	`ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `PERMISSION` varchar(32) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL,
    PRIMARY KEY (`ID`),
  UNIQUE KEY `PERMISSION` (`PERMISSION`)
);

DROP TABLE `ROLES_PERMISSIONS` ;
CREATE TABLE `ROLES_PERMISSIONS` (
  `ROLE_ID` smallint(6) NOT NULL,
  `PERMISSION_ID` smallint(6) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `MODIFIEDBY`  bigint(20) NOT NULL DEFAULT '0',
   `CREATED_DATE` timestamp NOT NULL,
   `MODIFIED_DATE` timestamp NOT NULL,
);